### ISSUE TITLE
Feature: Translations (to Dutch)

### ISSUE THREAD

**Issue by henkjanborghuis** [caleb531/youversion-suggest#1]
Hi,

Is it possible to alter this workflow to support Dutch as well?
If you can point me to a specific place in the code, I might be able to change it myself. 

Kind regards,
Henk Jan Borghuis

**Comment by caleb531** [comment]
Hi, Henk. I'm so glad you asked!

I've recently been working tirelessly on YouVersion Suggest v2, which will bring full multilanguage support. The workflow will only support English and Spanish out of the box, however support for any other language can be added relatively easily.

All of my latest work on v2 is available on the `feature/v2` branch. I hope to merge those changes into `master` in the coming days, but I'm still looking over the API to ensure that this is what I want to support for the long term. However, you are still very welcome to fork the `feature/v2` branch, check out the README, and begin adding support for Dutch. If you have any questions, please let me know and I will be happy to assist.

Caleb

**Comment by caleb531** [comment]
Actually, @henkjanborghuis, never mind about what I said. I've recently been working on a script which will automatically gather Bible data for any language that you wish to add. Therefore, once I make a few more improvements to the API, I will add support for the YouVersion Bible in Dutch. :)

Caleb

**Comment by caleb531** [comment]
Hello, again.

I'm pleased to inform you that I've just released YouVersion Suggest v2, and for your convenience, support for Dutch is built into YouVersion. See the README for details on changing your preferred language within the workflow itself.

**Comment by henkjanborghuis** [comment]
Hi Caleb,

Thank you for releasing the update.
I've tried the new workflow and it works like a charm.

Kind regards,
Henk Jan Borghuis
