### ISSUE TITLE
Add support for Swedish (sv)

### ISSUE THREAD

**Issue by MrMaFurb** [caleb531/youversion-suggest#5]
Hi!

Just find Your Alfred workflow.

I use the iphone app and it would be grate to search You Version online in Swedish too

**Comment by caleb531** [comment]
Will do! However, I need to set a default version in the language file before I commit. Therefore, please look through the list of Swedish Bible versions at the top of [this list](https://www.bible.com/sv/versions) and tell me which one is the most popular/widely-used.

Thanks,
Caleb

**Comment by caleb531** [comment]
Okay, I've added Swedish (sv) support on `develop` branch. @MrMaFurb, please download and test the workflow and let me know if that works for you. :)

Caleb
