### ISSUE TITLE
Add support for Finnish (fi)

### ISSUE THREAD

**Issue by Tamppi** [caleb531/youversion-suggest#6]
Hey

First, I'm sorry by poor English language. Would it be possible to get into that YouVersion-suggest workflow Finnish language. As well as all Finnish translations of the Bible
Giving thanks in advance.
Esa.A

**Comment by caleb531** [comment]
Yes, @Tamppi, I can absolutely add support for Finnish. However, there are four Finnish versions/translations available on the YouVersion website, and I must choose one to be the default version. Therefore, please look at the top of [this list](https://www.bible.com/fi/versions) and tell me which of the four versions should be the default version for Finnish.

Thanks,
Caleb

**Comment by Tamppi** [comment]
Hey

Thanks for your prompt contact. Default translations of the Bible should be the ”Kirkkoraamattu1992 (KR92)"
This is a really good workflow :) Thanks
TV. Esa

**Comment by caleb531** [comment]
Okay, @Tamppi, I've finished adding support for Finnish. Please install the [updated workflow](https://github.com/caleb531/youversion-suggest/blob/develop/YouVersion%20Suggest.alfredworkflow) and let me know how that works for you. :)

Caleb

**Comment by Tamppi** [comment]
Quick action.
Works perfectly :)

Thank you very much

**Comment by caleb531** [comment]
Excellent! Glad it works for you. :)

Also, @Tamppi, if you enjoy using YouVersion Suggest, please take a moment to **Star** the repository at the top of the page. That helps me know who's using it. :)

Caleb
