### ISSUE TITLE
Add support for Traditional Chinese (zh-TW)

### ISSUE THREAD

**Issue by phoenixwu** [caleb531/youversion-suggest#7]
Please add support for
Traditional-Chinese zh-TW，繁體中文
https://www.bible.com/zh-TW/languages/zho_tw

thanks a lot～

**Comment by caleb531** [comment]
Yes, I can certainly add support for traditional Chinese. I only have one question for you:

The link you provided lists six different versions for traditional Chinese. Which one should I choose to be the default version? Granted, any user can change their preferred version later, but I need to choose one version to be the default when users initially select traditional Chinese as their preferred language. I figure you know (much better than I do) which versions are more popular.

Thanks,
Caleb

**Comment by phoenixwu** [comment]
sure！
the most popular Chinese version is (CUNP-神)
https://www.bible.com/zh-TW/versions/46-cunp-xin-biao-dian-he-he-ben-shen-ban

many thanks

**Comment by caleb531** [comment]
Alright, @phoenixwu, I have just pushed YouVersion Suggest v7.1.0 ([download here](https://github.com/caleb531/youversion-suggest/raw/b208872ea073a753b52d706aefb57708f5b74485/YouVersion%20Suggest%20(Alfred%203).alfredworkflow) with support for Traditional Chinese (zh-TW), as you have requested. Please try it and let me know how it works for you. :)

Caleb

**Comment by phoenixwu** [comment]
It works perfectly!
Thanx!! 👍

**Comment by caleb531** [comment]
My pleasure, @phoenixwu! Thank you for using YouVersion Suggest! :)
